### ISSUE TITLE
That model is currently overloaded with other requests.

### ISSUE THREAD

**Issue by Hakkadaikon** [Hakkadaikon/nostr-yaruo-bot#8]
# Summary
7/1 16:30:07, Exception occurred in yaruo.

```
/home/hakkadaikon/repos/run/nostr-yaruo-bot/node_modules/openai/node_modules/axios/lib/core/createError.js:16
  var error = new Error(message);
              ^

Error: Request failed with status code 503
    at createError (/home/hakkadaikon/repos/run/nostr-yaruo-bot/node_modules/openai/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/hakkadaikon/repos/run/nostr-yaruo-bot/node_modules/openai/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/hakkadaikon/repos/run/nostr-yaruo-bot/node_modules/openai/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:523:35)
    at endReadableNT (node:internal/streams/readable:1367:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
~

    data: {
      error: {
        message: 'That model is currently overloaded with other requests. You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX in your message.)',
        type: 'server_error',
        param: null,
        code: null
      }
```

**Comment by Hakkadaikon** [comment]
ref: 
https://community.openai.com/t/status-code-503-that-model-is-currently-overloaded-with-other-requests/31433

**Comment by Hakkadaikon** [comment]
This exception may be thrown when the OpenAI Server is overloaded.
Added try-catch to prevent abnormal termination even if an exception is thrown.
